name: Test Coverage

on: [push, pull_request]

permissions:
  contents: read

env:
  COVERAGE: PartialSummary

jobs:
  test:
    name: ${{matrix.ruby}} on ${{matrix.os}} ${{matrix.gemfile}}
    runs-on: ${{matrix.os}}-latest
    env:
      BUNDLE_GEMFILE: ${{matrix.gemfile}}
    
    strategy:
      matrix:
        os:
          - ubuntu

        ruby:
          - "3.4"
        
        gemfile:
          - gems/rack-v1.rb
          - gems/rack-v2.rb
          - gems/rack-v30.rb
          - gems/rack-v31.rb
    
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{matrix.ruby}}
        bundler-cache: true
    
    - name: Run tests
      timeout-minutes: 5
      run: bundle exec bake test
    
    - uses: actions/upload-artifact@v4
      with:
        include-hidden-files: true
        if-no-files-found: error
        name: coverage-${{matrix.os}}-${{matrix.ruby}}-${{hashFiles(matrix.gemfile)}}
        path: .covered.db
  
  validate:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ruby
        bundler-cache: true
    
    - uses: actions/download-artifact@v4
    
    - name: Validate coverage
      timeout-minutes: 5
      run: bundle exec bake covered:validate --paths */.covered.db \;
